<?php

namespace App\Http\Controllers;

use Auth0\Laravel\Facade\Auth0;
use Illuminate\Http\Response;
use Illuminate\View\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\JsonResponse; // これを使用する

class Auth0Controller extends Controller
{
    // モックの大会データ
    private $tournaments;

    public function __construct()
    {
        $this->tournaments = [
            (object) [
                'id' => 1,
                'rank' => 'Jr',
                'title' => '森下仁丹2025大阪府キッズモーグル大会 第１戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '長野県',
                'place' => '長野県北安曇郡小谷村 白馬乗鞍温泉スキー場',
                'course' => 'ラビットコース',
                'association' => '大阪府',
                'race_date' => '45675',
                'category' => 'Jr',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5465',
                'codex_sajm' => '0465',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 2,
                'rank' => 'Jr',
                'title' => '森下仁丹2025大阪府キッズモーグル大会 第２戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '長野県北安曇郡小谷村 白馬乗鞍温泉スキー場',
                'course' => 'ラビットコース',
                'association' => '大阪府',
                'race_date' => '45676',
                'category' => 'Jr',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5466',
                'codex_sajm' => '0466',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 3,
                'rank' => 'SAJ-A',
                'title' => '第25回ばんけいモーグル競技会第１戦A級',
                'fistitle' => 'FIS Snowboard Japan Cup 2025 in Sapporo Bankei',
                'season' => '2024/2025',
                'pref' => '北海道',
                'place' => '札幌市 ばんけいスキー場',
                'course' => 'モーグルコース',
                'association' => '北海道',
                'race_date' => '45689',
                'category' => 'A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5447',
                'codex_sajm' => '0447',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 4,
                'rank' => 'SAJ-B',
                'title' => '第25回ばんけいモーグル競技会第１戦B級',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '札幌市 ばんけいスキー場',
                'course' => 'モーグルコース',
                'association' => '北海道',
                'race_date' => '45682',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5448',
                'codex_sajm' => '0448',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 5,
                'rank' => 'SAJ-A',
                'title' => '第25回ばんけいモーグル競技会第２戦A級',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '札幌市 ばんけいスキー場',
                'course' => 'モーグルコース',
                'association' => '北海道',
                'race_date' => '45690',
                'category' => 'A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5449',
                'codex_sajm' => '0449',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 6,
                'rank' => 'SAJ-B',
                'title' => '第25回ばんけいモーグル競技会第２戦B級',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '札幌市 ばんけいスキー場',
                'course' => 'モーグルコース',
                'association' => '北海道',
                'race_date' => '45683',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5450',
                'codex_sajm' => '0450',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 7,
                'rank' => 'SAJ-B',
                'title' => '2025HSCフリースタイルスキー選手権大会　B級モーグル大会　第１戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '長野県',
                'place' => null,
                'course' => null,
                'association' => '長野県',
                'race_date' => '45689',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5495',
                'codex_sajm' => '0495',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 8,
                'rank' => 'SAJ-B',
                'title' => '2025HSCフリースタイルスキー選手権大会　B級モーグル大会　第２戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => null,
                'course' => null,
                'association' => '長野県',
                'race_date' => '45690',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5496',
                'codex_sajm' => '0496',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 9,
                'rank' => 'FIS/A',
                'title' => '第43回長野県フリースタイルスキー選手権大会　モーグル競技',
                'fistitle' => 'The43rd Nagano Freestyleski Championship Moguls',
                'season' => '2024/2025',
                'pref' => '長野県',
                'place' => '北安曇郡白馬村 白馬五竜いいもりゲレンデ',
                'course' => 'DISCOVERYモーグルコース',
                'association' => '長野県',
                'race_date' => '45692',
                'category' => 'FIS/A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5456',
                'codex_sajm' => '0456',
                'codex_fisf' => '8464',
                'codex_fism' => '8463',
            ],
            (object) [
                'id' => 10,
                'rank' => 'FIS/A',
                'title' => '2025HSCフリースタイルスキー選手権大会　モーグル大会',
                'fistitle' => '2025HSC Freestyleski Championship Moguls',
                'season' => '2024/2025',
                'pref' => '長野県',
                'place' => '北安曇郡白馬村 白馬五竜いいもりゲレンデ',
                'course' => 'DISCOVERYモーグルコース',
                'association' => '長野県',
                'race_date' => '45693',
                'category' => 'FIS/A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5457',
                'codex_sajm' => '0457',
                'codex_fisf' => '8462',
                'codex_fism' => '8461',
            ],
            (object) [
                'id' => 11,
                'rank' => 'SAJ-B',
                'title' => '森下仁丹2025大阪府はくのりモーグル大会 第１戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '長野県',
                'place' => '長野県北安曇郡小谷村 白馬乗鞍温泉スキー場',
                'course' => 'ラビットコース',
                'association' => '大阪府',
                'race_date' => '45696',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5468',
                'codex_sajm' => '0468',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 12,
                'rank' => 'SAJ-B',
                'title' => '森下仁丹2025大阪府はくのりモーグル大会 第２戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '長野県北安曇郡小谷村 白馬乗鞍温泉スキー場',
                'course' => 'ラビットコース',
                'association' => '大阪府',
                'race_date' => '45697',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5469',
                'codex_sajm' => '0469',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 13,
                'rank' => 'SAJ-A',
                'title' => '2025フリースタイルスキー秋田・田沢湖モーグル競技会 MO',
                'fistitle' => '2025 FREESTYLE SKI AKITA TAZAWAKO MOGUL COMPETITION',
                'season' => '2024/2025',
                'pref' => '秋田県',
                'place' => '仙北市  たざわ湖スキー場',
                'course' => '黒森山モーグルコース',
                'association' => '秋田県',
                'race_date' => '45696',
                'category' => 'A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5471',
                'codex_sajm' => '0471',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 14,
                'rank' => 'SAJ-B',
                'title' => '2025フリースタイルスキー秋田・田沢湖モーグル競技会 MO',
                'fistitle' => '2025 FREESTYLE SKI AKITA TAZAWAKO MOGUL COMPETITION',
                'season' => '2024/2025',
                'pref' => null,
                'place' => '仙北市  たざわ湖スキー場',
                'course' => '黒森山モーグルコース',
                'association' => '秋田県',
                'race_date' => '45696',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5472',
                'codex_sajm' => '0472',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 15,
                'rank' => 'SAJ-A',
                'title' => '2025フリースタイルスキー秋田・田沢湖モーグル競技会 DM',
                'fistitle' => '2025 FREESTYLE SKI AKITA TAZAWAKO MOGUL COMPETITION',
                'season' => '2024/2025',
                'pref' => null,
                'place' => '仙北市  たざわ湖スキー場',
                'course' => '黒森山モーグルコース',
                'association' => '秋田県',
                'race_date' => '45697',
                'category' => 'A',
                'discipline' => 'DM',
                'sex' => '男女',
                'codex_sajf' => '5473',
                'codex_sajm' => '0473',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 16,
                'rank' => 'SAJ-B',
                'title' => '2025フリースタイルスキー秋田・田沢湖モーグル競技会 DM',
                'fistitle' => '2025 FREESTYLE SKI AKITA TAZAWAKO MOGUL COMPETITION',
                'season' => '2024/2025',
                'pref' => null,
                'place' => '仙北市  たざわ湖スキー場',
                'course' => '黒森山モーグルコース',
                'association' => '秋田県',
                'race_date' => '45697',
                'category' => 'B',
                'discipline' => 'DM',
                'sex' => '男女',
                'codex_sajf' => '5474',
                'codex_sajm' => '0474',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 17,
                'rank' => 'SAJ-B',
                'title' => '2025きはしクリニック東海北陸ブロックモーグル競技会  第１戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '岐阜県',
                'place' => '郡上市高鷲町 ホワイトピアたかす',
                'course' => 'センターウェイAコース',
                'association' => '岐阜県',
                'race_date' => '45703',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5454',
                'codex_sajm' => '0454',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 18,
                'rank' => 'SAJ-B',
                'title' => '2026きはしクリニック東海北陸ブロックモーグル競技会  第２戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '郡上市高鷲町 ホワイトピアたかす',
                'course' => 'センターウェイAコース',
                'association' => '岐阜県',
                'race_date' => '45704',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5455',
                'codex_sajm' => '0455',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 19,
                'rank' => 'SAJ-A',
                'title' => '2025 白馬乗鞍埼玉県モーグル選手権大会  第１戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '長野県',
                'place' => '長野県北安曇郡小谷村 白馬乗鞍温泉スキー場',
                'course' => 'ラビットコース',
                'association' => '埼玉県',
                'race_date' => '45703',
                'category' => 'A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5476',
                'codex_sajm' => '0476',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 20,
                'rank' => 'SAJ-A',
                'title' => '2025 白馬乗鞍埼玉県モーグル選手権大会  第２戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '長野県北安曇郡小谷村 白馬乗鞍温泉スキー場',
                'course' => 'ラビットコース',
                'association' => '埼玉県',
                'race_date' => '45704',
                'category' => 'A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5477',
                'codex_sajm' => '0477',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 21,
                'rank' => 'FIS/A',
                'title' => '第44回北海道スキー選手権大会フリースタイル競技DM種目',
                'fistitle' => '44th HOKKAIDO Ski Championship Freestyle DM',
                'season' => '2024/2025',
                'pref' => '北海道',
                'place' => '札幌市 ばんけいスキー場',
                'course' => 'モーグルコース',
                'association' => '北海道',
                'race_date' => '45711',
                'category' => 'FIS/A',
                'discipline' => 'DM',
                'sex' => '男女',
                'codex_sajf' => '5451',
                'codex_sajm' => '0451',
                'codex_fisf' => '8470',
                'codex_fism' => '8469',
            ],
            (object) [
                'id' => 22,
                'rank' => 'FIS/A',
                'title' => '第44回北海道スキー選手権大会フリースタイル競技MO種目',
                'fistitle' => '44th HOKKAIDO Ski Championship Freestyle MO',
                'season' => '2024/2025',
                'pref' => null,
                'place' => '札幌市 ばんけいスキー場',
                'course' => 'モーグルコース',
                'association' => '北海道',
                'race_date' => '45712',
                'category' => 'FIS/A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5452',
                'codex_sajm' => '0452',
                'codex_fisf' => '8472',
                'codex_fism' => '8471',
            ],
            (object) [
                'id' => 23,
                'rank' => 'FIS/A',
                'title' => '第96回宮様スキー大会国際競技会',
                'fistitle' => 'The 96th International MIYASAMA Ski Games',
                'season' => '2024/2025',
                'pref' => '北海道',
                'place' => '札幌市 ばんけいスキー場',
                'course' => 'モーグルコース',
                'association' => '北海道',
                'race_date' => '45717',
                'category' => 'FIS/A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5478',
                'codex_sajm' => '0478',
                'codex_fisf' => '8474',
                'codex_fism' => '8473',
            ],
            (object) [
                'id' => 24,
                'rank' => 'SAJ-B',
                'title' => '第２５回埼玉県松之山温泉モーグル競技会',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '新潟県',
                'place' => '十日町市松之山 松之山温泉スキー場',
                'course' => 'パラダイスモーグルコース',
                'association' => '埼玉県',
                'race_date' => '45717',
                'category' => 'B',
                'discipline' => 'DM',
                'sex' => '男女',
                'codex_sajf' => '5475',
                'codex_sajm' => '0475',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 25,
                'rank' => 'SAJ-B',
                'title' => '令和6年度新潟県スキー選手権大会兼第23回国体記念松之山温泉モーグル競技会',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '新潟県',
                'place' => '十日町市松之山 松之山温泉スキー場',
                'course' => 'パラダイスモーグルコース',
                'association' => '新潟県',
                'race_date' => '45718',
                'category' => 'B',
                'discipline' => 'DM',
                'sex' => '男女',
                'codex_sajf' => '5453',
                'codex_sajm' => '0453',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 26,
                'rank' => 'FIS ASIA/A',
                'title' => 'アジアカップ　第34回札幌モーグル競技会',
                'fistitle' => 'Asia Cup 34th SAPPORO Moguls Competition 2025',
                'season' => '2024/2025',
                'pref' => '北海道',
                'place' => '札幌市 ばんけいスキー場',
                'course' => 'モーグルコース',
                'association' => '北海道',
                'race_date' => '45718',
                'category' => 'FIS ASIA/A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5479',
                'codex_sajm' => '0479',
                'codex_fisf' => '8518',
                'codex_fism' => '8517',
            ],
            (object) [
                'id' => 27,
                'rank' => 'FIS ASIA/A',
                'title' => '2025 アジアカップ　たいら　モーグル競技会/2025 世界遺産五箇山フリースタイルスキー選手権大会第1戦',
                'fistitle' => '2025 Asian Cup Taira Moguls Competition/2025 World Heritage Gokayama Freestyle Ski Championships Round1',
                'season' => '2024/2025',
                'pref' => '富山県',
                'place' => '南砺市 たいらスキー場',
                'course' => 'ダイナミックコース',
                'association' => '富山県',
                'race_date' => '45724',
                'category' => 'FIS ASIA/A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5441',
                'codex_sajm' => '0441',
                'codex_fisf' => '8476',
                'codex_fism' => '8475',
            ],
            (object) [
                'id' => 28,
                'rank' => 'FIS ASIA/A',
                'title' => '2025 アジアカップ　たいら　モーグル競技会/2025 世界遺産五箇山フリースタイルスキー選手権大会第2戦',
                'fistitle' => '2025 Asian Cup Taira Moguls Competition/2025 World Heritage Gokayama Freestyle Ski Championships Round2',
                'season' => '2024/2025',
                'pref' => null,
                'place' => '南砺市 たいらスキー場',
                'course' => 'ダイナミックコース',
                'association' => '富山県',
                'race_date' => '45725',
                'category' => 'FIS ASIA/A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5442',
                'codex_sajm' => '0442',
                'codex_fisf' => '8478',
                'codex_fism' => '8477',
            ],
            (object) [
                'id' => 29,
                'rank' => 'SAJ-A',
                'title' => '2025イマトクCUPハチ北モーグル大会 第１戦A級',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '兵庫県',
                'place' => '美方郡香美町 ハチ北スキー場',
                'course' => 'スーパーモーグルコース',
                'association' => '兵庫県',
                'race_date' => '45724',
                'category' => 'A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5458',
                'codex_sajm' => '0458',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 30,
                'rank' => 'SAJ-A',
                'title' => '2025イマトクCUPハチ北モーグル大会 第１戦B級',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '美方郡香美町 ハチ北スキー場',
                'course' => 'スーパーモーグルコース',
                'association' => '兵庫県',
                'race_date' => '45724',
                'category' => 'A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5459',
                'codex_sajm' => '0459',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 31,
                'rank' => 'SAJ-A',
                'title' => '2025イマトクCUPハチ北モーグル大会 第２戦A級',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '美方郡香美町 ハチ北スキー場',
                'course' => 'スーパーモーグルコース',
                'association' => '兵庫県',
                'race_date' => '45725',
                'category' => 'A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5460',
                'codex_sajm' => '0460',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 32,
                'rank' => 'SAJ-A',
                'title' => '2025イマトクCUPハチ北モーグル大会 第２戦B級',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '美方郡香美町 ハチ北スキー場',
                'course' => 'スーパーモーグルコース',
                'association' => '兵庫県',
                'race_date' => '45725',
                'category' => 'A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5461',
                'codex_sajm' => '0461',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 33,
                'rank' => 'NJC',
                'title' => '2025全日本ジュニアスキー選手権大会フリースタイル競技MO種目 中学',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '富山県',
                'place' => '南砺市 たいらスキー場',
                'course' => 'ダイナミックコース',
                'association' => '富山県',
                'race_date' => '45731',
                'category' => 'NJC',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5435',
                'codex_sajm' => '0435',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 34,
                'rank' => 'NJC',
                'title' => '2025全日本ジュニアスキー選手権大会フリースタイル競技MO種目 高校',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '南砺市 たいらスキー場',
                'course' => 'ダイナミックコース',
                'association' => '富山県',
                'race_date' => '45731',
                'category' => 'NJC',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5436',
                'codex_sajm' => '0436',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 35,
                'rank' => 'NJC',
                'title' => '2025全日本ジュニアスキー選手権大会フリースタイル競技DM種目 中学',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '南砺市 たいらスキー場',
                'course' => 'ダイナミックコース',
                'association' => '富山県',
                'race_date' => '45732',
                'category' => 'NJC',
                'discipline' => 'DM',
                'sex' => '男女',
                'codex_sajf' => '5437',
                'codex_sajm' => '0437',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 36,
                'rank' => 'NJC',
                'title' => '2025全日本ジュニアスキー選手権大会フリースタイル競技DM種目 高校',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '南砺市 たいらスキー場',
                'course' => 'ダイナミックコース',
                'association' => '富山県',
                'race_date' => '45732',
                'category' => 'NJC',
                'discipline' => 'DM',
                'sex' => '男女',
                'codex_sajf' => '5438',
                'codex_sajm' => '0438',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 37,
                'rank' => 'SAJ-B',
                'title' => '森下仁丹2025大阪府はくのりモーグル大会  第１戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '長野県',
                'place' => '長野県北安曇郡小谷村 白馬乗鞍温泉スキー場',
                'course' => 'ラビットコース',
                'association' => '大阪府',
                'race_date' => '45738',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5463',
                'codex_sajm' => '0463',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 38,
                'rank' => 'SAJ-B',
                'title' => '森下仁丹2025大阪府はくのりモーグル大会  第２戦',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => null,
                'place' => '長野県北安曇郡小谷村 白馬乗鞍温泉スキー場',
                'course' => 'ラビットコース',
                'association' => '大阪府',
                'race_date' => '45739',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5464',
                'codex_sajm' => '0464',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 39,
                'rank' => 'NC',
                'title' => '第45回全日本スキー選手権大会フリースタイル競技　種目：DM',
                'fistitle' => 'The 45th All Japan Ski Championships Freestyle DM',
                'season' => '2024/2025',
                'pref' => '北海道',
                'place' => '札幌市 ばんけいスキー場',
                'course' => 'モーグルコース',
                'association' => '北海道',
                'race_date' => '45745',
                'category' => 'NC',
                'discipline' => 'DM',
                'sex' => '男女',
                'codex_sajf' => '5443',
                'codex_sajm' => '0443',
                'codex_fisf' => '8482',
                'codex_fism' => '8481',
            ],
            (object) [
                'id' => 40,
                'rank' => 'NC',
                'title' => '第45回全日本スキー選手権大会フリースタイル競技　種目：MO',
                'fistitle' => 'The 45th All Japan Ski Championships Freestyle MO',
                'season' => '2024/2025',
                'pref' => null,
                'place' => '札幌市 ばんけいスキー場',
                'course' => 'モーグルコース',
                'association' => '北海道',
                'race_date' => '45746',
                'category' => 'NC',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5444',
                'codex_sajm' => '0444',
                'codex_fisf' => '8486',
                'codex_fism' => '8485',
            ],
            (object) [
                'id' => 41,
                'rank' => 'SAJ-B',
                'title' => '2025フリースタイルふくしま大会',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '福島県',
                'place' => 'グランデコスノーリゾート',
                'course' => 'グランデコスノーリゾート・フリーライド',
                'association' => '福島県',
                'race_date' => '45752',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5467',
                'codex_sajm' => '0467',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 42,
                'rank' => 'SAJ-B',
                'title' => '第２６回東京都モーグル競技会',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '福島県',
                'place' => 'グランデコスノーリゾート',
                'course' => 'グランデコスノーリゾート・フリーライド',
                'association' => '東京都',
                'race_date' => '45753',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5470',
                'codex_sajm' => '0470',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 43,
                'rank' => '非公認',
                'title' => '2025WC北米セレクション',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '富山県',
                'place' => '南砺市 たいらスキー場',
                'course' => 'ダイナミックコース',
                'association' => '富山',
                'race_date' => '45666',
                'category' => 'A',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '5499',
                'codex_sajm' => '0499',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 44,
                'rank' => '非公認',
                'title' => '2025WMC',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '北海道',
                'place' => '札幌市 ばんけいスキー場',
                'course' => 'モーグルコース',
                'association' => 'WSS',
                'race_date' => '45753',
                'category' => null,
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '9003',
                'codex_sajm' => '0003',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
            (object) [
                'id' => 45,
                'rank' => '非公認',
                'title' => 'リザルトシステム練習用',
                'fistitle' => null,
                'season' => '2024/2025',
                'pref' => '東京都',
                'place' => '東京都',
                'course' => '東京都',
                'association' => '東京',
                'race_date' => '45657',
                'category' => 'B',
                'discipline' => 'MO',
                'sex' => '男女',
                'codex_sajf' => '9004',
                'codex_sajm' => '8004',
                'codex_fisf' => null,
                'codex_fism' => null,
            ],
                        // 他のモックデータ
        ];
    }

    public function showLoginPrompt(): View
    {
        return view('auth.login-prompt');
    }

    public function showLoggedOut(): View
    {
        return view('auth.logged-out');
    }

    public function showDashboard(): View
    {
        return view('dashboard');
    }



    public function private(): Response
    {
        return response('Welcome! You are logged in.');
    }

    public function scope(): Response
    {
        return response('You have `read:messages` permission, and can therefore access this resource.');
    }

    public function index(): Response|RedirectResponse
    {
        if (! auth()->check()) {
            return redirect()->route('login'); // 未ログイン時はログイン誘導画面へリダイレクト
        }

        $user = auth()->user();
        $name = $user->name ?? 'User';
        $email = $user->email ?? '';

        return response("Hello {$name}! Your email address is {$email}.");
    }

    public function colors(): Response
    {
        $endpoint = Auth0::management()->users();

        $colors = ['red', 'blue', 'green', 'black', 'white', 'yellow', 'purple', 'orange', 'pink', 'brown'];

        $endpoint->update(
            id: auth()->id(),
            body: [
                'user_metadata' => [
                    'color' => $colors[random_int(0, count($colors) - 1)]
                ]
            ]
        );

        $metadata = $endpoint->get(auth()->id()); // Retrieve the user's metadata.
        $metadata = Auth0::json($metadata); // Convert the JSON to a PHP array.

        $color = $metadata['user_metadata']['color'] ?? 'unknown';
        $name = auth()->user()->name;

        return response("Hello {$name}! Your favorite color is {$color}.");
    }

    public function logout(): RedirectResponse
    {
        Auth::logout();
        return redirect()->route('logout');
    }

    public function showTournamentSelect(): View
    {
        //$tournaments = Tournament::with(['prefecture', 'skiResort', 'discipline', 'category'])->get();
        return view('tournaments.select', ['tournaments' => $this->tournaments]);
    }

    public function getTournamentDetails(int $id): JsonResponse
    {
        //$tournament = Tournament::with(['prefecture', 'skiResort', 'discipline', 'category'])->findOrFail($id);
        //return response()->json($tournament);
        // モックデータから指定された ID の大会を検索
        $tournament = collect($this->tournaments)->firstWhere('id', $id);

        if ($tournament) {
            return response()->json($tournament);
        } else {
            return response()->json(['message' => '大会情報が見つかりません'], 404);
        }

    }
}
